name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (if required)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Example - Use Azure OpenAI Secret
        env:
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
        run: |
          echo "Using Azure OpenAI Endpoint: $AZURE_OPENAI_ENDPOINT"
          # Your script commands here...

      - name: Example - SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Example - Service User Credentials
        env:
          USERNAME: ${{ secrets.BND_TC_SVC_USER }}
          PASSWORD: ${{ secrets.BND_TC_SVC_PASS }}
        run: |
          echo "Login using username $USERNAME"
          # Your authentication commands here...
